[package]
name = "cli"
version.workspace = true
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true, features = ["derive"] }
ionic = { path = "../parser" }
regex = { workspace = true }
rayon = { workspace = true }
mimalloc = { version = "0.1.48" }
crc32fast = "1.5.0"

[[bin]]
name = "ionic"
path = "src/main.rs"
