// Compile-time generated tables from `spec-derived/*.toml`.
//
// Re-exported from the build script output, plus const lookup functions
// for transport attrs/elements that operate on byte slices.

// Tables generated by build.rs from spec-derived/*.toml.
#[allow(dead_code)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/semantic_tables.rs"));
}

// Re-export the generated lookup and sorted tables.
pub use generated::{cv_value_type, IDREF_ATTRS, OPTIONAL_ELEMENTS, REQUIRED_ELEMENTS};

/// Transport attributes to suppress in semantic mode.
///
/// This is the **single source of truth** — both the counter/derived attrs
/// from the schema and the IDREF cross-references that are bookkeeping.
/// Sorted at compile time for binary search.
const TRANSPORT_ATTRS: &[&[u8]] = &[
    b"arrayLength",
    b"count",
    b"cvRef",
    b"dataProcessingRef",
    b"defaultArrayLength",
    b"defaultDataProcessingRef",
    b"defaultInstrumentConfigurationRef",
    b"defaultSourceFileRef",
    b"encodedLength",
    b"index",
    b"instrumentConfigurationRef",
    b"sampleRef",
    b"scanSettingsRef",
    b"softwareRef",
    b"sourceFileRef",
    b"spotID",
];

/// Elements to skip entirely in semantic mode.
const TRANSPORT_ELEMENTS: &[&[u8]] = &[
    b"fileChecksum",
    b"index",
    b"indexList",
    b"indexListOffset",
    b"indexedmzML",
    b"offset",
];

/// Check if an attribute name should be suppressed in semantic mode.
#[inline]
pub fn is_transport_attr(name: &[u8]) -> bool {
    TRANSPORT_ATTRS.binary_search(&name).is_ok()
}

/// Check if an element should be entirely skipped in semantic mode.
#[inline]
pub fn is_transport_element(name: &[u8]) -> bool {
    TRANSPORT_ELEMENTS.binary_search(&name).is_ok()
}
