[package]
name = "mzml-diff"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
blake3 = "1.5.5"
clap = { workspace = true, features = ["derive"] }
hashbrown = "0.16.1"
quick-xml = { workspace = true }
rayon = { workspace = true }

[build-dependencies]
toml = "0.8"
serde = { workspace = true }

[[bin]]
name = "mzml-diff"
path = "src/main.rs"

[[bin]]
name = "spec-compiler"
path = "src/bin/spec-compiler.rs"
