name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    name: test (${{ matrix.target }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - os: windows-latest
            target: x86_64-pc-windows-msvc

          - os: macos-15-intel
            target: x86_64-apple-darwin

          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu

          - os: macos-latest
            target: aarch64-apple-darwin

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}
          cache-key: ${{ matrix.target }}
          rustflags: ""

      - name: Run tests
        run: cargo test --all-features --target ${{ matrix.target }}

  test-wasm:
    name: test (wasm32 byte_transpose)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown
          cache-key: wasm32-byte-transpose
          rustflags: ""

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Run tests
        run: wasm-pack test --node .github/workflows/byte_transpose_wasm
